name: Build and Push Docker Image To AWS ECR
on: workflow_dispatch

jobs:
  build-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Make application-prod.properties
      run: |
        mkdir -p ./src/main/resources
        cd ./src/main/resources
        touch ./application.properties
        echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./application.properties
      shell: bash
      
    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew clean build -x test
      
    - name: Naming jar file
      run: |
        ls ./build/libs/
        mv ./build/libs/demo-0.0.1-SNAPSHOT.jar ./build/libs/app.jar

    - name: Check jar file
      run: ls ./build/libs

    - uses: actions/upload-artifact@v4
      with:
        name: app
        path: ./build/libs/app.jar
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR Private
      id: login-ecr-private
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: private

    - name: Build, tag, and push docker image to Amazon ECR Private
      env:
        REGISTRY: ${{ steps.login-ecr-private.outputs.registry }}
        REGISTRY_ALIAS: ${{ secrets.PRIVATE_ECR_ID }}
        REPOSITORY: app-with-ecs
        IMAGE_TAG: latest
      run: |
        aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ secrets.PRIVATE_ECR_ID }}
        docker build -t $REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
