name: App With Github Actions with docker-compose CI/CD

on: workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    # 현재 브랜치의 코드를 체크아웃
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Make application-prod.properties
      run: |
	mkdir -p ./src/main/resources
        cd ./src/main/resources
        touch ./application.properties
        echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./application.properties
      shell: bash
      
    - name: Build with Gradle
      run: ./gradlew clean build -x test
      
    - name: Naming jar file
      run: mv ./build/libs/*.jar ./build/libs/app.jar

    - name: Check jar file
      run: ls ./build/libs

    - uses: actions/upload-artifact@v4
      with:
        name: app
        path: ./build/libs/*.jar

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/app-with-actions:latest
 
