name: App With Github Actions with docker-compose CI/CD

on: push

jobs: 
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Make application-prod.properties
      run: |
        mkdir -p ./src/main/resources
        cd ./src/main/resources
        touch ./application.properties
        echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./application.properties
      shell: bash
      
    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew clean build -x test
      
    - name: Naming jar file
      run: |
        ls ./build/libs/
        mv ./build/libs/demo-0.0.1-SNAPSHOT.jar ./build/libs/appl.jar

    - name: Check jar file
      run: ls ./build/libs

    - uses: actions/upload-artifact@v4
      with:
        name: app
        path: ./build/libs/appl.jar

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/app-for-cicd-test:latest
  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
    - name: Execute deployment script
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
            cd
            cat docker.compose.yml
            sudo docker-compose down
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/app-for-cicd-test
            sudo docker-compose up -d
    
